name: Deploy CYBERCORE Web

on:
  push:
    branches: ["main"] # Якщо твоя головна гілка називається master, зміни на ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Configuration and Secrets
          run: |
            echo "const CONFIG = { TELEGRAM_TOKEN: '${{ secrets.TG_TOKEN }}', TELEGRAM_CHAT_ID: '${{ secrets.TG_CHAT_ID }}', DB_SECRET_KEY: '${{ secrets.DB_SECRET_KEY }}' };" > config.js
            echo "const supabaseUrl = '${{ secrets.SUPABASE_URL }}';" >> config.js
            echo "const supabaseKey = '${{ secrets.SUPABASE_KEY }}';" >> config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4